import type { Metadata } from 'next';
import './globals.css';
import { dejaVuSans } from './utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${dejaVuSans.variable}`}>
      <body className="">{children}</body>
    </html>
  );
}
